use_frameworks!

platform :ios, '10.0'

target 'ImageDownloaderMesrop_Example' do
  pod 'ImageDownloaderMesrop', :path => '../'

  target 'ImageDownloaderMesrop_Tests' do
    inherit! :search_paths

    
  end
end
